### PR TITLE
Clean up dependencies

### PR DESCRIPTION
**Pull request by bootstraponline**
- Replace snake_case with camelCase
- Fix hardcoded selenium version in selendroid-client
- Move json string into rootProject.ext

### CODE REVIEW

**Comment by bootstraponline** [comment]
gradle clean build  fails for me with:

> :selendroid-server:transformClassesWithDexForDebug FAILED
> 
> Caused by: com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)

**Comment by bootstraponline** [comment]
I'm using

```
$ java -version
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)
```

**Comment by bootstraponline** [comment]
Another build error:

```
java.lang.StackOverflowError
    at com.sun.tools.javac.comp.Attr.attribArgs(Attr.java:658)
    at com.sun.tools.javac.comp.Attr.visitApply(Attr.java:1806)
```

> :selendroid-server:compileDebugJavaWithJavac

**Comment by vishals79** [comment]
We were using Java for the build
Java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)

**Comment by vishals79** [comment]
_Changes done to_
    - Replace snake_case with camelCase
    - Fix hardcoded selenium version in selendroid-client
    - Move json string into rootProject.ext

**Comment by vishals79** [comment]
Increased stack size to 1550k using **GRADLE_OPTS="-Xss1500k"** to fix
java.lang.StackOverflowError
    at com.sun.tools.javac.comp.Attr.attribArgs(Attr.java:658)
    at com.sun.tools.javac.comp.Attr.visitApply(Attr.java:1806)

**Comment by vishals79** [comment]
Added _java source and target version = 1.7_ in _selendroid-server-common_ _build.gradle_
**sourceCompatibility = 1.7**
**targetCompatibility = 1.7**

to fix
    :selendroid-server:transformClassesWithDexForDebug FAILED

```
Caused by: com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
```

**Comment by vishals79** [comment]
Changes present in gradle-build-system and master branch that's why closing the pull request.

**Pull request closed without merging**
